### ISSUE TITLE
Content aggregation checklist

### ISSUE THREAD

**Issue by caseyg** [caseyg/melchua#6]
To aggregate:

- [x] blog posts from wordpress
- [x] updated CV
- [ ] drawings from scribd
- [ ] presentations from slideshare
- [ ] any talks we'd want to do with a transcript / accessible video player
- [x] for interpreters page

To write:

- [x] intro text for each page

**Comment by mchua** [comment]
the "For interpreters" part is going to basically be http://bit.ly/mel-terp-letter - that can be used as an initial content set.

**Comment by caseyg** [comment]
mel will put more drawings into dropbox, when scribd isn't hanging:

https://www.dropbox.com/home/work/melchua/melchua%20website%20files

**Comment by mchua** [comment]
I updated the descriptions on the scholarship, self, and sketches sections (not the main one, since that may get revamped anyway) - they're more formal but I'm still scratching my head on the scholarship one.
